
server:
  port: 8081
  version: 1.0.0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: org.mysise.demo1.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: testdb
      password: Z2cEcbLhXLSE6Fj3
      driver-class-name: com.mysql.jdbc.Driver
      #初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      test-on-borrow: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      pool-prepared-statements: true
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      min-evictable-idle-time-millis: 300000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      max-wait: 60000
      test-on-return: false
  application:
    name: demo1-dubbo-provider
  aop:
    auto: true
    proxy-target-class: true

  dubbo:
    server: true
    #    scan: org.mysise.user.service
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881