server:
  port: 8079
spring:
  aop:
    proxy-target-class: true
  application:
    name: demo-dubbo-gateway

  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: consumer
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://localhost:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。
      name: dubbo
      port: 20880
    consumer:
      check: true
    reference:
      loadbalance: roundrobin #轮询机制
      #loadbalance: random #随机机制